# Generated by Django 5.2.5 on 2025-11-04 17:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('school_id', models.CharField(db_index=True, max_length=100)),
                ('alert_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('anomaly_score', models.FloatField()),
                ('affected_systems', models.JSONField(default=list)),
                ('summary', models.TextField()),
                ('log_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], db_index=True, default='new', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'alert_level'], name='api_alert_timesta_30018e_idx'), models.Index(fields=['status', '-timestamp'], name='api_alert_status_904dfe_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('school_id', models.CharField(db_index=True, max_length=100)),
                ('total_logs_processed', models.IntegerField(default=0)),
                ('normal_logs', models.IntegerField(default=0)),
                ('anomalous_logs', models.IntegerField(default=0)),
                ('parsing_coverage', models.FloatField(default=0.0)),
                ('templates_extracted', models.IntegerField(default=0)),
                ('processing_time_seconds', models.FloatField(default=0.0)),
                ('logs_per_second', models.FloatField(default=0.0)),
                ('source_breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='api_logstat_timesta_4c793d_idx'), models.Index(fields=['school_id', '-timestamp'], name='api_logstat_school__5f81fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='RawModelOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('school_id', models.CharField(db_index=True, max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('log_sequence', models.TextField()),
                ('masked_predictions', models.JSONField()),
                ('anomaly_scores', models.JSONField()),
                ('attention_weights', models.JSONField(blank=True, null=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='api_rawmode_timesta_afaae4_idx'), models.Index(fields=['is_anomaly', '-timestamp'], name='api_rawmode_is_anom_735ca9_idx'), models.Index(fields=['school_id', 'model_name', '-timestamp'], name='api_rawmode_school__43c248_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('school_id', models.CharField(db_index=True, max_length=100)),
                ('metric_type', models.CharField(db_index=True, max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', '-timestamp'], name='api_systemm_metric__85dc90_idx'), models.Index(fields=['school_id', '-timestamp'], name='api_systemm_school__93b790_idx')],
            },
        ),
    ]
