# Generated by Django 5.2.5 on 2025-11-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalSystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kafka_status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=20)),
                ('kafka_details', models.TextField(default='No status received from local network')),
                ('zookeeper_status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=20)),
                ('zookeeper_details', models.TextField(default='No status received from local network')),
                ('consumer_status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=20)),
                ('consumer_details', models.TextField(default='No status received from local network')),
                ('overall_status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Local System Status',
                'verbose_name_plural': 'Local System Statuses',
                'ordering': ['-last_updated'],
            },
        ),
    ]
