# Generated by Django 4.2.7 on 2025-08-03 07:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('host_ip', models.CharField(max_length=45)),
                ('log_message', models.TextField()),
                ('source', models.CharField(blank=True, max_length=100)),
                ('log_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Log Entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_threshold', models.FloatField(default=0.5)),
                ('kafka_broker_url', models.CharField(default='localhost:9092', max_length=200)),
                ('kafka_topic_logs', models.CharField(default='logs', max_length=100)),
                ('kafka_topic_anomalies', models.CharField(default='anomalies', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('details', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'System Statuses',
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_score', models.FloatField()),
                ('threshold', models.FloatField(default=0.5)),
                ('is_anomaly', models.BooleanField(default=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='dashboard.logentry')),
            ],
            options={
                'verbose_name_plural': 'Anomalies',
                'ordering': ['-detected_at'],
            },
        ),
    ]
