# Generated by Django 5.2.5 on 2025-08-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
