# Generated by Django 5.2.5 on 2025-10-06 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_anomaly_acknowledged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='acknowledged',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='anomaly_score',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='detected_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='is_anomaly',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='host_ip',
            field=models.CharField(db_index=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='log_type',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['detected_at', 'is_anomaly'], name='dashboard_a_detecte_93c150_idx'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['anomaly_score', 'detected_at'], name='dashboard_a_anomaly_c4b283_idx'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['acknowledged', 'detected_at'], name='dashboard_a_acknowl_d529a4_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['timestamp', 'log_type'], name='dashboard_l_timesta_3013df_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['host_ip', 'timestamp'], name='dashboard_l_host_ip_a85ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['source', 'timestamp'], name='dashboard_l_source_71ced5_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['log_type', 'timestamp'], name='dashboard_l_log_typ_c68e69_idx'),
        ),
    ]
