# Generated by Django 5.2.5 on 2025-11-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatIntelligenceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=45, unique=True)),
                ('vt_malicious', models.IntegerField(blank=True, null=True)),
                ('vt_suspicious', models.IntegerField(blank=True, null=True)),
                ('vt_harmless', models.IntegerField(blank=True, null=True)),
                ('vt_undetected', models.IntegerField(blank=True, null=True)),
                ('vt_reputation', models.IntegerField(blank=True, null=True)),
                ('vt_country', models.CharField(blank=True, max_length=100, null=True)),
                ('vt_asn', models.CharField(blank=True, max_length=100, null=True)),
                ('vt_as_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('vt_last_analysis_date', models.CharField(blank=True, max_length=100, null=True)),
                ('vt_flagged_engines', models.JSONField(blank=True, null=True)),
                ('vt_queried_at', models.DateTimeField(blank=True, null=True)),
                ('abuseipdb_confidence_score', models.IntegerField(blank=True, null=True)),
                ('abuseipdb_total_reports', models.IntegerField(blank=True, null=True)),
                ('abuseipdb_num_distinct_users', models.IntegerField(blank=True, null=True)),
                ('abuseipdb_country', models.CharField(blank=True, max_length=100, null=True)),
                ('abuseipdb_isp', models.CharField(blank=True, max_length=255, null=True)),
                ('abuseipdb_usage_type', models.CharField(blank=True, max_length=100, null=True)),
                ('abuseipdb_categories', models.JSONField(blank=True, null=True)),
                ('abuseipdb_is_whitelisted', models.BooleanField(default=False)),
                ('abuseipdb_last_reported_at', models.CharField(blank=True, max_length=100, null=True)),
                ('abuseipdb_queried_at', models.DateTimeField(blank=True, null=True)),
                ('shodan_hostnames', models.JSONField(blank=True, null=True)),
                ('shodan_domains', models.JSONField(blank=True, null=True)),
                ('shodan_ports', models.JSONField(blank=True, null=True)),
                ('shodan_vulns', models.JSONField(blank=True, null=True)),
                ('shodan_cpes', models.JSONField(blank=True, null=True)),
                ('shodan_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('shodan_os', models.CharField(blank=True, max_length=100, null=True)),
                ('shodan_country', models.CharField(blank=True, max_length=100, null=True)),
                ('shodan_city', models.CharField(blank=True, max_length=100, null=True)),
                ('shodan_isp', models.CharField(blank=True, max_length=255, null=True)),
                ('shodan_tags', models.JSONField(blank=True, null=True)),
                ('shodan_last_update', models.CharField(blank=True, max_length=100, null=True)),
                ('shodan_queried_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Threat Intelligence Cache',
                'verbose_name_plural': 'Threat Intelligence Cache',
                'indexes': [models.Index(fields=['ip_address', 'updated_at'], name='dashboard_t_ip_addr_904ac9_idx')],
            },
        ),
    ]
