# Generated by Django 6.0 on 2026-01-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_threatintelligencecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='classification_class',
            field=models.IntegerField(blank=True, db_index=True, help_text='Class number (0-6): 0=Normal, 1=Security, 2=System Failure, 3=Performance, 4=Network, 5=Config, 6=Hardware', null=True),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='classification_name',
            field=models.CharField(blank=True, db_index=True, help_text="Human-readable class name (e.g., 'Security Anomaly')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='severity',
            field=models.CharField(blank=True, choices=[('info', 'Info'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, help_text='Severity level: info, medium, high, critical', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['classification_class', 'detected_at'], name='dashboard_a_classif_e8d243_idx'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['severity', 'detected_at'], name='dashboard_a_severit_8b0685_idx'),
        ),
    ]
