# Generated by Django 6.0 on 2026-01-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_anomaly_classification_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='anomaly_score',
            field=models.FloatField(blank=True, db_index=True, help_text='Anomaly score from model (0.0-1.0)', null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='classification_class',
            field=models.IntegerField(blank=True, db_index=True, help_text='Class number (0-6): 0=Normal, 1=Security, 2=System Failure, 3=Performance, 4=Network, 5=Config, 6=Hardware', null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='classification_name',
            field=models.CharField(blank=True, db_index=True, help_text="Human-readable class name (e.g., 'Normal', 'Security Anomaly')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='severity',
            field=models.CharField(blank=True, db_index=True, help_text='Severity level: info, medium, high, critical', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['classification_class', 'timestamp'], name='dashboard_l_classif_28253a_idx'),
        ),
    ]
